Priveasy/Priveasy/urls.py
from django.contrib import admin
from django.urls import path , include

urlpatterns = [
    path('TheOfficeIsTheBestShowEver/', admin.site.urls),
    path('' , include('mainSite.urls')),
]

Priveasy/mainSite/urls.py
from django.urls import path
from django.contrib.auth import views as authViews
from . import views

urlpatterns = [
				path('' , views.home , name = 'home'),
				path('account/' , views.account , name = 'account'),
				path('register/' , views.register , name = 'register'),
				path('paste/<slug:slug>/' , views.pastes , name = 'pastes'),
				path('logout/' , authViews.LogoutView.as_view() , name = 'logout'),
				path('change/password/' , authViews.PasswordChangeView.as_view(), name = 'password_change'),
				path('change/password/done/' , authViews.PasswordChangeDoneView.as_view() , name = 'password_change_done'),
				path('password/reset/' , authViews.PasswordResetView.as_view() , name = 'password_reset'),
				path('password/reset/done/' , authViews.PasswordResetDoneView.as_view() , name = 'password_reset_done'),
				path('password/reset/link/<uidb64>/<token>/' , authViews.PasswordResetConfirmView.as_view() , name = 'password_reset_confirm'),
				path('password/reset/confirm/done/' , authViews.PasswordResetCompleteView.as_view() , name = 'password_reset_complete'),
				path('account/purchase/' , views.purchase , name = 'purchase'),
				path('account/purchase/crypto/' , views.cryptoPayment , name = 'cryptoPayment'),
				path('vpn/download/<slug:slug>/' , views.vpnDownload , name = 'vpnDownload'),
				path('policies/<slug:slug>/' , views.policies , name = 'policies'),
				path('config/<slug:slug>' , views.config , name = 'config'),
				path('verify/<slug:slug>' , views.verify , name = 'verify'),
				path('<slug:slug>/' , views.short , name = 'short')
			]

Priveasy/mainSite/models.py
from django.db import models
from django.conf import settings
import uuid

class Stats(models.Model):
	# Page View Stats:
	homeViews = models.IntegerField('Number of times the home page was viewed' , default = 0)
	accountViews = models.IntegerField('Number of times an account page was viewed' , default = 0)
	registerViews = models.IntegerField('Number of times the register page was viewed' , default = 0)
	termsViews = models.IntegerField('Number of times the Terms were viewed' , default = 0)
	privacyPolicyViews = models.IntegerField('Number of times the Privacy Policy was viewed' , default = 0)
	cryptoPageViews = models.IntegerField('Number of times the cryptocurrency purchase page was viewed' , default = 0)
	purchasePageViews = models.IntegerField('Number of times the purchase page was viewed' , default = 0)
	publicPasteViews = models.IntegerField('Number of times a public paste was successfully viewed' , default = 0)
	shortenedURLClicks = models.IntegerField('Number of times a shortened URL was clicked' , default = 0)
	vpnDownloads = models.IntegerField('Number of times a VPN profile was downloaded' , default = 0)
	shadowsocksViews = models.IntegerField('Number of times shadowsocks connection info was viewed' , default = 0)
	priveasy404Views = models.IntegerField('Number of times a 404 page was intentionally displayed for Priveasy.org' , default = 0)
	p5vc404Views = models.IntegerField('Number of times a 404 page was intentionally displayed for P5.vc' , default = 0)



class AccountContents(models.Model):
	def genSecret():
		return str(uuid.uuid4())


	user = models.OneToOneField(settings.AUTH_USER_MODEL , on_delete = models.CASCADE)

	# Account Data:
	accountCreated = models.DateTimeField('Account created' , auto_now_add = True)
	accountLastUpdated = models.DateTimeField('Account last updated' , auto_now = True)
	accountSecret = models.CharField('Account secret' , max_length = 36 , default = genSecret) # To be transmitted to the user via an external method, and used for action verifications
	emailVerified = models.BooleanField('Account email verified' , default = False)

	# Plan Data:
	planType = models.IntegerField('Plan number' , default = 0)
	planExpiration = models.IntegerField('Plan expiration' , default = 0)

	# Payment Data:
	autoRenew = models.BooleanField('Auto renew enabled' , default = False)
	longRenew = models.BooleanField('Renew for six months' , default = False)
	stripeID = models.CharField('Stripe customer ID' , max_length = 36 , blank = True)

	# Restrict Email Sends:
	emailsRemaining = models.IntegerField('Emails remaining' , default = 0)

	# Restrict Text Sends:
	textsRemaining = models.IntegerField('Texts remaining' , default = 0)

	# Restrict Referral Code Use:
	refCodeUsed = models.BooleanField('A referral code has been used' , default = False)

	# VPN Data:
	vpnPersistence = models.BooleanField('VPN profile persists through server upgrades' , default = False)



class VPNServer(models.Model):
	# Generate and return unique VPN server ID:
	def createServerID():
		while (True):
			id = ('server' + str(uuid.uuid4()).replace('-' , ''))[0:14]
			try:
				VPNServer.objects.get(serverID = id)
				continue
			except:
				return id


	serverID = models.CharField('Server ID' , max_length = 14 , default = createServerID)
	# For server type, 1 = Domestic and 2 = Offshore
	serverType = models.IntegerField('Server type' , default = 0)
	serverIP = models.GenericIPAddressField('Server IP address')



class VPNProfile(models.Model):
	server = models.ForeignKey(VPNServer , null = True , on_delete = models.CASCADE)
	account = models.ForeignKey(AccountContents , on_delete = models.CASCADE)

	# Generate and return unique VPN profile usernames:
	def createUsername():
		while (True):
			username = ('user' + str(uuid.uuid4()).replace('-' , ''))[0:14]
			try:
				VPNProfile.objects.get(vpnUsername = username)
				continue
			except:
				return username


	# Return the default VPN server:
	def returnDefaultServer():
		serverObj = VPNServer.objects.get(id = 1)
		return serverObj


	vpnUsername = models.CharField('VPN username' , max_length = 14 , default = createUsername)
	vpnProfileNum = models.IntegerField('VPN profile number' , default = 0)



class Paste(models.Model):
	account = models.ForeignKey(AccountContents , on_delete = models.CASCADE)

	# Generate and return unique paste ID:
	def createPasteID():
		while (True):
			tempPasteID = ((str(uuid.uuid4())).replace('-' , ''))[0:10]
			try:
				Paste.objects.get(pasteID = tempPasteID)
				continue
			except:
				return tempPasteID


	pasteID = models.CharField('Paste ID' , max_length = 10 , default = createPasteID)
	public = models.BooleanField('Paste is public' , default = False)
	# Allow 1MB per paste:
	contents = models.TextField('Paste contents' , max_length = 1000000 , blank = True)



class EmailForwarder(models.Model):
	account = models.ForeignKey(AccountContents , on_delete = models.CASCADE)

	def generateForwarder():
		while (True):
			email = (((str(uuid.uuid4()).replace('-' , ''))[0:8]) + '@fwd.priveasy.org')
			try:
				EmailForwarder.objects.get(fowarder = email)
				continue
			except:
				return email


	def createVerifID():
		return str(uuid.uuid4())


	verified = models.BooleanField('Email has been verified' , default = False)
	verifID = models.CharField('Verification String' , max_length = 36 , default = createVerifID)

	forwarder = models.EmailField('Email forwarder' , default = generateForwarder)
	forwardTo = models.EmailField('Forward to' , blank = True)



class ShortenedURL(models.Model):
	account = models.ForeignKey(AccountContents , on_delete = models.CASCADE)

	def generateURL():
		while (True):
			url = ((str(uuid.uuid4())).replace('-' , ''))[0:6]
			try:
				ShortenedURL.objects.get(slug = url)
				continue
			except:
				return url


	destinationURL = models.URLField('Destination URL' , max_length = 2000)
	slug = models.CharField('URL slug' , max_length = 6 , default = generateURL)
	clicks = models.IntegerField('Number of clicks' , default = 0)



class ReferralCode(models.Model):
	account = models.OneToOneField(AccountContents , on_delete = models.CASCADE)

	# Generate and return a unique referral code:
	def createReferralCode():
		while (True):
			tempCode = ((str(uuid.uuid4()).replace('-' , ''))[0:12])
			try:
				ReferralCode.objects.get(code = tempCode)
				continue
			except:
				return tempCode


	code = models.CharField('Referral code' , max_length = 12 , default = createReferralCode)



class ZcashPaymentAddresses(models.Model):
	account = models.OneToOneField(AccountContents , on_delete = models.CASCADE)

	requested = models.BooleanField('Addresses Requested' , default = False)
	generated = models.BooleanField('Addresses Generated' , default = False)

	shieldedAddress = models.CharField('Zcash Shielded Payment Address' , max_length = 100 , blank = True)
	transparentAddress = models.CharField('Zcash Transparent Payment Address' , max_length = 50 , blank = True)



class Discount(models.Model):
	# Generate and return a unique referral code:
	def createCouponCode():
		while (True):
			tempCode = ((str(uuid.uuid4()).replace('-' , ''))[0:10])
			try:
				Discount.objects.get(code = tempCode)
				continue
			except:
				return tempCode


	# Make sure the code, if manually entered, is lowercase
	code = models.CharField('Discount code' , max_length = 64 , default = createCouponCode)
	message = models.TextField('Emailed success message' , max_length = 10000 , default = 'Hello,\nThank you so much for using a discount code at checkout! We\'re just sending you this quick email to let you know that it was successfully applied. Have a nice day!\n- Priveasy\'s Friendly Server Bot')
	timeAdded = models.IntegerField('Amount of time to add to current plan' , default = 0)
	expiration = models.IntegerField('Discount code expiration' , default = 0)
	timesUsed = models.IntegerField('Number of times used' , default = 0)



# A model designed to send emails to users; objects will never be saved to database:
class EmailUsers(models.Model):
	sendTo = models.CharField('Recipient (if more than one, separate with a single space)' , max_length = 500 , default = 'Admin@Priveasy.org')

	sentFrom = models.CharField('Email address to send from' , max_length = 500 , default = 'Server@NoReply.Priveasy.org')

	subject = models.CharField('Email subject' , max_length = 500 , default = 'An Email From Priveasy')

	message = models.TextField('Email Message' , max_length = 10000 , default = 'Hello,\nI just wanted to reach out and quickly say thank you for using Priveasy! I really appreciate you!\n- Priveasy\'s Friendly Server Bot' , blank = True)

	standardNotificationTemplate = models.BooleanField('Use standard, HTML, notification template' , default = False)

	autoBCC = models.BooleanField('Automatically BCC multiple "to" addresses' , default = True)

	sendToVPNUsers = models.BooleanField('Automatically send email to all VPN users' , default = False)

	sendToAllUsers = models.BooleanField('Automatically send email to all users' , default = False)


	# Define custom save bahavior as to not touch the database:
	def save(self, *args, **kwargs):
		from .tasks import sendEmail
		sendEmail.delay(self.subject , self.message , self.sentFrom , self.sendTo.split() , standardNotificationTemplate = self.standardNotificationTemplate , autoBCC = self.autoBCC , sendToVPNUsers = self.sendToVPNUsers , sendToAllUsers = self.sendToAllUsers)

Priveasy/mainSite/forms.py
from django import forms
from django.contrib.auth.models import User


class UserRegistrationForm(forms.ModelForm):
	password = forms.CharField(label = 'Password' , widget = forms.PasswordInput)
	passwordAgain = forms.CharField(label = 'Repeat Password' , widget = forms.PasswordInput)

	class Meta:
		model = User
		fields = ('username' , 'first_name' , 'email')

	def cleanPasswordAgain(self):
		cd = self.cleaned_data
		if (cd['password'] != cd['passwordAgain']):
			raise forms.ValidationError('Passwords do not match.')
		return cd['passwordAgain']


class LoginForm(forms.Form):
	username = forms.CharField()
	password = forms.CharField(widget = forms.PasswordInput)


class TextSendForm(forms.Form):
	recipientNumber = forms.CharField(label = 'recipientNumber' , max_length = 11)
	message = forms.CharField(widget = forms.Textarea , max_length = 140)

Priveasy/mainSite/templates/fullscreenMessage.html
{% load static %}
<!doctype html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
        <link rel="icon" sizes="192x192" href="{% static "icons/GrayscaleIcon.png" %}">
        <meta http-equiv="refresh" content="{{ delay }}; url={{ redirectURL }}" />
        <title>{{ title }}</title>
        <link href="{% static "css/bootstrap.css" %}" rel="stylesheet">
        <link href="{% static "css/fullscreen.css" %}" rel="stylesheet">
    </head>
    <body class="text-center">
            <h1 class="h3 mb-3 font-weight-normal"><a href="{{ redirectURL }}" style="color: #686868; font-weight: bolder;">{{ message }}</a></h1>
    </body>
</html>

Priveasy/mainSite/templates/purchase.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
        <title>Purchase a Plan</title>
        <link rel="apple-touch-icon" href="{% static "icons/AppleIcon.png" %}">
    	<link rel="icon" sizes="192x192" href="{% static "icons/Icon.png" %}">
    	<link rel="shortcut icon" href="{% static "icons/ShortcutIcon.png" %}">
        <link href="{% static "css/bootstrap.css" %}" rel="stylesheet">
        <link href="{% static "css/register.css" %}" rel="stylesheet">
        <link href="{% static "css/stripe.css" %}" rel="stylesheet">
    </head>
    <body>
        <div class="container">
            <div class="row vertical-center">
                <div class="col-lg-10 col-xl-9 mx-auto">
                    <div class="card card-signin flex-row my-5">
                        <div class="card-img-left d-none d-md-flex">
                        </div>
                        <div class="card-body">
                            <h5 class="card-title text-center" style="margin-bottom: 0px;">Purchase a Plan</h5>
                            <form class="form-signin" action="." method="post" id="payment-form">
                            <div style="margin-top: 15px; margin-bottom: 15px; text-align: center;">{% if request.user.accountcontents.planType != 0 %}
                                <h6>If you wish to change your current plan (plan #{{ request.user.accountcontents.planType }}), please{% if request.user.accountcontents.autoRenew %} cancel auto recharge and{% endif %} wait for it to expire, or <a href="{% url "register" %}">create a new account</a>.</h6>{% endif %}
                                <div style="margin-top: 10px; margin-bottom: 15px;">
                                    <h5><a href="{% url "home" %}#Plans">Review Plan Options</a></h5>
                                    <h5><a href="{% url "cryptoPayment" %}">Pay With Cryptocurrency</a></h5>
                                </div>
                            </div>{% if request.user.accountcontents.autoRenew %}
                            <div class="form-label-group">
                                <input type="hidden" name="autoRenew" value="Cancel">
                                {% csrf_token %}
                            </div>
                            <button class="btn btn-lg btn-primary btn-block text-uppercase" type="submit">Cancel Auto Recharge</button>
                            </form>{% else %}
                            <div class="form-label-group">
                                <p><select name="planType" id="id_planType" class="form-control">
                                {% if request.user.accountcontents.planType == 1 %}
                                    <option value="1" selected>$2 - Extend Plan By 30 Days</option>
                                    <option value="2">$12 - Extend Plan By 180 Days</option>
                                {% elif request.user.accountcontents.planType == 2 %}
                                    <option value="1" selected>$4.00 - Extend Plan By 30 Days</option>
                                    <option value="2">$22.50 - Extend Plan By 180 Days</option>
                                {% elif request.user.accountcontents.planType == 3 %}
                                    <option value="1" selected>$5.00 - Extend Plan By 30 Days</option>
                                    <option value="2">$28.50 - Extend Plan By 180 Days</option>
                                {% else %}
                                    <option value="1" selected>Plan 1 (30 Days) - $2.00</option>
                                    <option value="2">Plan 1 (180 Days) - $12.00</option>
                                    <option value="3">Plan 2 (30 Days) - $4.00</option>
                                    <option value="4">Plan 2 (180 Days) - $22.50</option>
                                    <option value="5">Plan 3 (30 Days) - $5.00</option>
                                    <option value="6">Plan 3 (180 Days) - $28.50</option>
                                {% endif %}
                                </select></p>
                            </div>
                            <div class="form-label-group">
                                <input type="text" id="referral_code" name="referral_code" maxlength="15" class="form-control" placeholder="Referral/Coupon Code">
                                    <label for="referral_code">Referral/Coupon Code</label>
                                </div>
                                <div class="custom-control custom-checkbox">
                                    <input type="checkbox" class="custom-control-input" id="autoRenew" name="autoRenew" value="Yes">
                                    <label class="custom-control-label" for="autoRenew">Automatically Recharge My Card</label>
                                </div>
                                <hr>
                                <p><div id="card-element"><!-- A Stripe Element will be inserted here. --></div> </p>
                                <!-- Used to display form errors. -->
                                <p><div id="card-errors" role="alert"></div> </p>
                                {% csrf_token %}
                                <div style="margin-top: 15px; margin-bottom: 15px; text-align: center;">
                                    <h6>By clicking "Submit Payment", I acknowledge that I have read and agree to the <a href="{% url "home" %}policies/1/">Privacy Statement</a> and <a href="{% url "home" %}policies/2/">Terms of Service</a>, as well as any terms of service found at <a href="https://stripe.com/legal">Stripe.com</a>.</h6>
                                </div>
                                <button class="btn btn-lg btn-primary btn-block text-uppercase" type="submit">Submit Payment</button>
                            </form>{% endif %}
                        </div>
                    </div>
                </div>
            </div>
        </div>
        {% if not request.user.accountcontents.autoRenew %}
            <!-- Stripe payment resources -->
            <script src="https://js.stripe.com/v3/"></script>
            <script src="{% static "js/stripe.js" %}"></script>
        {% endif %}
    </body>
</html>

Priveasy/mainSite/templates/register.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
        <link rel="icon" sizes="192x192" href="{% static "icons/Icon.png" %}">
        <title>Create An Account</title>
        <link href="{% static "css/bootstrap.css" %}" rel="stylesheet">
        <link href="{% static "css/register.css" %}" rel="stylesheet">
    </head>
    <body>
        <div class="container">
            <div class="row vertical-center">
                <div class="col-lg-10 col-xl-9 mx-auto">
                    <div class="card card-signin flex-row my-5">
                        <div class="card-img-left d-none d-md-flex">
                        </div>
                        <div class="card-body">
                            <h5 class="card-title text-center">Create an Account</h5>
                            <form class="form-signin" action="." method="post">
                                {% if errors %}
                                    <div style="margin-top: 15px; margin-bottom: 15px; text-align: center;">
                                        <h5>Form Error(s):</h5>
                                        {% for error in errors %}
                                            <h6 class="text-danger">{{ error }}</h6>
                                        {% endfor %}
                                    </div>
                                {% endif %}
                                <div class="form-label-group">
                                    <input type="text" name="username" maxlength="150" id="id_username" class="form-control" placeholder="Username" required autofocus>
                                    <label for="id_username">Username</label>
                                </div>
                                <div class="form-label-group">
                                    <input type="text" id="id_first_name" name="first_name" maxlength="30" class="form-control" placeholder="First Name" required>
                                    <label for="id_first_name">First Name</label>
                                </div>
                                <div class="form-label-group">
                                    <input type="email" name="email" maxlength="254" id="id_email" class="form-control" placeholder="Email address" required>
                                    <label for="id_email">Email Address</label>
                                </div>
                                <hr>
                                <div class="form-label-group">
                                    <input type="password" name="password" id="id_password" class="form-control" placeholder="Password" required>
                                    <label for="id_password">Password</label>
                                </div>
                                <div class="form-label-group">
                                    <input type="password" name="passwordAgain" id="id_passwordAgain" class="form-control" placeholder="Password" required>
                                    <label for="id_passwordAgain">Confirm Password</label>
                                </div>
                                {% csrf_token %}
                                <div style="margin-top: 15px; margin-bottom: 15px; text-align: center;">
                                    <h6>By clicking "Register", I acknowledge that I have read and agree to the <a href="{% url "home" %}policies/1/">Privacy Statement</a> and <a href="{% url "home" %}policies/2/">Terms of Service</a>.</h6>
                                </div>
                                <button class="btn btn-lg btn-primary btn-block text-uppercase" type="submit">Register</button>
                                <a class="d-block text-center mt-2 small" href="{% url "home" %}#Login">Sign In</a>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </body>
</html>

Priveasy/mainSite/templates/vpnSelection.html
{% load static %}
<!doctype html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
        <meta name="description" content="">
        <meta name="author" content="">
        <title>VPN Profile Selection</title>
        <link href="{% static "css/bootstrap.css" %}" rel="stylesheet">
        <link href="{% static "css/fullscreen.css" %}" rel="stylesheet">
    </head>
    <body class="text-center">
            <h1 class="h3 mb-3 font-weight-normal">
			{% if request.user.accountcontents.planType == 2 %}
			<a href="{% url "vpnDownload" slug1 %}" style="color: #686868; font-weight: bolder;">Domestic Profile 1</a>
			<br>
			<a href="{% url "vpnDownload" slug2 %}" style="color: #686868; font-weight: bolder;">Domestic Profile 2</a>
			<br>
			<a href="{% url "account" %}" style="color: #686868; font-weight: bolder;">Back</a>
			{% elif request.user.accountcontents.planType == 3 %}
			<a href="{% url "vpnDownload" slug1 %}" style="color: #686868; font-weight: bolder;">Domestic Profile 1</a>
			<br>
			<a href="{% url "vpnDownload" slug2 %}" style="color: #686868; font-weight: bolder;">Domestic Profile 2</a>
			<br>
			<a href="{% url "vpnDownload" slug3 %}" style="color: #686868; font-weight: bolder;">Domestic Profile 3</a>
			<br>
			<a href="{% url "vpnDownload" slug4 %}" style="color: #686868; font-weight: bolder;">Domestic Profile 4</a>
			<br>
			<a href="{% url "vpnDownload" slug5 %}" style="color: #686868; font-weight: bolder;">Domestic Profile 5</a>
			<br>
			<a href="{% url "vpnDownload" slug6 %}" style="color: #686868; font-weight: bolder;">Offshore Profile 1</a>
			<br>
			<a href="{% url "vpnDownload" slug7 %}" style="color: #686868; font-weight: bolder;">Offshore Profile 2</a>
			<br>
			<a href="{% url "vpnDownload" slug8 %}" style="color: #686868; font-weight: bolder;">Offshore Profile 3</a>
			<br>
			<a href="{% url "vpnDownload" slug9 %}" style="color: #686868; font-weight: bolder;">Offshore Profile 4</a>
			<br>
			<a href="{% url "vpnDownload" slug10 %}" style="color: #686868; font-weight: bolder;">Offshore Profile 5</a>
			<br>
			<a href="{% url "account" %}" style="color: #686868; font-weight: bolder;">Back</a>
			{% else %}
			<a href="{% url "account" %}" style="color: #686868; font-weight: bolder;">You must have plan #2 or plan #3 to access this page.</a>
			<br>
			<a href="{% url "account" %}" style="color: #686868; font-weight: bolder;">Back</a>
			{% endif %}
			</h1>
    </body>
</html>